apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cerebro.fullname" . }}
  labels:
    {{- include "cerebro.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "cerebro.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "cerebro.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: cerebro
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 9000
              protocol: TCP
          env:
            - name: OPENSEARCH_HOSTS
              value: "https://{{ .Values.opensearch.endpoint }}"
            - name: AWS_REGION
              value: "{{ .Values.opensearch.region }}"
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}